### PR TITLE
sbt-paradox 0.10.6

### PR DESCRIPTION
**Pull request by mkurz**
@johanandren Same game again, can you merge if green and cut `v0.54` afterwards?

### CODE REVIEW

**Comment by mkurz** [comment]
@johanandren Green :+1:

**Review by johanandren — APPROVED** [review]

**Comment by mkurz** [comment]
@johanandren I think a new release would make sense.

**Comment by johanandren** [comment]
We just need another thing merged on our end before I'll trigger a release.

**Comment by johanandren** [comment]
0.54 out now

**Pull request merged**
