### PR TITLE
Update lightbend banner

### PR DESCRIPTION
**Pull request by rasummer**
@ennru @patriknw Updated Lightbend Banner for the Akka docs websites. We are now ready to deploy. 

Screen Shot 2020-03-30 at 4 51 47 PM

### CODE REVIEW

**Comment by ennru** [comment]
I guess it uses the same code as akka.io, so it doesn't work in Firefox.
image

**Comment by ignasi35** [comment]
@ennru it must be something else.

It works for me in Firefox if I use an Incognito window but it doesn't when I use my regular session. I'm not sure what the difference is between the two.

Screenshot 2020-03-31 at 14 25 00

What's also strange is that akka.io works on my Firefox in both my regular session and Incognito, so I'm not sure I can reproduce your comment wrt akka.io.

**Comment by ennru** [comment]
I later understood that the Privacy Badger disliked the images from another domain.

**Comment by ennru** [comment]
@rasummer Will update the PRs to include the images.

**Pull request merged**
