### PR TITLE
Add Lightbend banner and Google Tag Manager

### PR DESCRIPTION
**Pull request by rasummer**
@patriknw ready for you and your team to review.

Added the Lightbend Banner - fully responsive.  

The sidebar TOC was moved over to css flexbox and css position sticky, as this allowed for the Lightbend banner to scroll out of view, but still have the TOC stick to the full viewport height. As such a whole bunch of CSS has changed.

Switched out old typesafe tracker google analytics with Google Tag Manager.

**Large Screen**
desktop-view

Also I fixed an issue where doc content was overly squashed on medium/tablet sized screens, see screen grab comparison.

**Issue on medium**
issue-medium-size

**Fixed on medium**
fixed-medium-size

### CODE REVIEW

**Comment by ennru** [comment]
It does not work for me in Firefox (MacOS) when applied to Alpakka (Chrome and Safari work).

bild

**Comment by raboof** [comment]
> https://github.com/akka/akka-grpc/pull/654/files#diff-bd58959d0ef01f941f2e2a00d2a788baR30

I seem to remember this was intended to allow for 'sidebar links', but I don't remember any pages actually using that, so great! Looks much better!

**Comment by rasummer** [comment]
@ennru I'll take a look at Alpakka on Firefox.

**Comment by rasummer** [comment]
@ennru I've download Alpakka and tried `sbt docs/previewSite`. It's throwing some errors:

```
[error] /Users/richardsummerhayes/src/alpakka/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApi.scala:26:27: could not find implicit value for parameter clock: java.time.Clock
[error]   def now: Long = JwtTime.nowSeconds
[error]                           ^
[error] /Users/richardsummerhayes/src/alpakka/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApi.scala:30:17: could not find implicit value for parameter clock: java.time.Clock
[error]       .expiresIn(3600)
[error]                 ^
[warn] /Users/richardsummerhayes/src/alpakka/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApi.scala:24:15: private val scope in class GoogleTokenApi is never used
[warn]   private val scope = "https://www.googleapis.com/auth/pubsub"
[warn]               ^
[error] /Users/richardsummerhayes/src/alpakka/google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/GoogleTokenApi.scala:29:27: could not find implicit value for parameter clock: java.time.Clock
[error]   def now: Long = JwtTime.nowSeconds
[error]                           ^
[error] /Users/richardsummerhayes/src/alpakka/google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/GoogleTokenApi.scala:33:17: could not find implicit value for parameter clock: java.time.Clock
[error]       .expiresIn(3600)
[error]
```

```
[info] No documentation generated with unsuccessful compiler run
[warn] 67 warnings found
[error] four errors found
[error] (Scalaunidoc / doc) Scaladoc generation failed
[error] Total time: 62 s, completed Aug 7, 2019 10:13:37 AM
```

I've tried it with and without the paradox snapshot.

**Comment by ennru** [comment]
You hit a rare scenario depending on classpath ordering. See https://github.com/akka/alpakka/pull/1869 to make that go away.

**Comment by rasummer** [comment]
@ennru Thanks for helping me get set up running Alpakka locally. I'm not seeing any issue on my version of firefox (MacOS) [https://whatsmybrowser.org/b/GNNTH9N](https://whatsmybrowser.org/b/GNNTH9N)

I only use my Firefox browser for testing websites, not day to day browsing, as such it's very clean, no plugins/extensions etc. Could you try clearing cache. 

**large**
alpakka-large

**medium**
alpakka-medium

**small**
alpakka-small

**Comment by ennru** [comment]
Yes, that was it. I have EFF's Privacy Badger installed in Firefox. It looked broken again, I allowed `doc.akka.io` once -- and after that, even with its default blocking the site looks great.
Thank you!

**Comment by raboof** [comment]
Let's do a release when #65 is also in?

**Comment by ennru** [comment]
And the copyright include file, please...

**Comment by raboof** [comment]
I don't currently have a need for that so I'd rather focus on different tasks - where would you want to see it used?

**Comment by ennru** [comment]
Akka Enhancements is where this started, right?

**Comment by raboof** [comment]
I think there the change in #65 should suffice?

**Comment by ennru** [comment]
Better than before at least, we could show the commercial license there. Rebase #65 and we are good to go.

**Comment by rasummer** [comment]
@patriknw @ennru @patriknw @raboof Any news on when this will roll out to the docs sites?

thanks Rich

**Comment by theotown** [comment]
Hey team, really looking forward to this push! If we didn't mention it before, doc.akka.io generates more traffic than any other domain or sub-domain of Lightbend. This will be an exciting addition to the UX. Please let us know how we can help!

**Comment by ennru** [comment]
We are ready for roll-out and I created https://github.com/akka/akka.github.com/issues/629 to track progress.

But. When I redeployed Alpakka Kafka docs the site broke for me. It worked locally but looked like this when served from doc.akka.io

image

**Comment by ennru** [comment]
I tried now to purge the Cloudflare cache now, but it doesn't make a difference.
I'll roll it back.

**Comment by ennru** [comment]
Ok, Johannes traced it down to being the `page.css` being cached by Cloudflare and me not using the Cloudflare tooling correctly.
Alpakka Kafka is not using the banner for version 1.0.5.

**Comment by jrudolph** [comment]
>  Alpakka Kafka is not using the banner for version 1.0.5.

is *now* ;)

**Comment by ennru** [comment]
Oops.

**Comment by theotown** [comment]
Works for me here: https://doc.akka.io/docs/alpakka-kafka/current/

**Comment by ennru** [comment]
We're getting there after a few bumps...
https://doc.akka.io/docs/alpakka/current/

**Comment by theotown** [comment]
Beautiful!

**Comment by rasummer** [comment]
Thanks everyone :)

**Pull request merged**
